"""initial schema

Revision ID: 2bc7d7397412
Revises: 
Create Date: 2026-09-10 05:21:00.304486
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2bc7d7397412'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_baselines',
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('rows_per_page', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('target')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('fetcher', sa.String(length=16), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('output_format', sa.String(length=8), nullable=False),
    sa.Column('incremental', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lost_worker_count', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=True),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('result_key', sa.Text(), nullable=True),
    sa.Column('result_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_pages > 0', name='ck_jobs_max_pages_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_api_key_id'), 'jobs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index('ix_jobs_state_created', 'jobs', ['state', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_target'), 'jobs', ['target'], unique=False)
    op.create_index('uq_jobs_idempotency_key', 'jobs', ['api_key_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_job_id'), 'dead_letters', ['job_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_reason'), 'dead_letters', ['reason'], unique=False)
    op.create_table('failed_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'page', name='uq_failed_pages_job_page')
    )
    op.create_index(op.f('ix_failed_pages_error_type'), 'failed_pages', ['error_type'], unique=False)
    op.create_index(op.f('ix_failed_pages_job_id'), 'failed_pages', ['job_id'], unique=False)
    op.create_table('job_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'page', name='uq_job_pages_job_page')
    )
    op.create_index('ix_job_pages_hash', 'job_pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_job_pages_job_id'), 'job_pages', ['job_id'], unique=False)
    op.create_table('target_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('row_key', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target', 'row_key', name='uq_target_snapshots_row')
    )
    op.create_index(op.f('ix_target_snapshots_target'), 'target_snapshots', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_snapshots_target'), table_name='target_snapshots')
    op.drop_table('target_snapshots')
    op.drop_index(op.f('ix_job_pages_job_id'), table_name='job_pages')
    op.drop_index('ix_job_pages_hash', table_name='job_pages')
    op.drop_table('job_pages')
    op.drop_index(op.f('ix_failed_pages_job_id'), table_name='failed_pages')
    op.drop_index(op.f('ix_failed_pages_error_type'), table_name='failed_pages')
    op.drop_table('failed_pages')
    op.drop_index(op.f('ix_dead_letters_reason'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_job_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_index('uq_jobs_idempotency_key', table_name='jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_jobs_target'), table_name='jobs')
    op.drop_index('ix_jobs_state_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_api_key_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('drift_baselines')
    # ### end Alembic commands ###
